name: pushing image
on: workflow_dispatch
jobs:
  python:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: image-name
          registry: 989813064368.dkr.ecr.us-west-2.amazonaws.com/testimage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
