name: pushing image
on: workflow_dispatch
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: pythonimage
          registry: public.ecr.aws/o7x1t6h0/sai
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
